- src/main/java/aibe1/proj2/mentoss/feature/account/controller/AccountController.java
- src/main/java/aibe1/proj2/mentoss/feature/account/model/dto/ProfileResponseDto.java
- src/main/java/aibe1/proj2/mentoss/feature/account/model/dto/ProfileUpdateRequestDto.java
- src/main/java/aibe1/proj2/mentoss/feature/account/model/mapper/AccountMapper.java
- src/main/java/aibe1/proj2/mentoss/feature/account/service/AccountService.java
- src/main/java/aibe1/proj2/mentoss/feature/account/service/AccountServiceImpl.java
- src/main/java/aibe1/proj2/mentoss/feature/login/service/CustomOAuth2UserService.java
- src/main/java/aibe1/proj2/mentoss/feature/login/service/OAuth2LoginSuccessHandler.java
- src/main/java/aibe1/proj2/mentoss/global/auth/CustomUserDetails.java
- src/main/java/aibe1/proj2/mentoss/global/auth/JwtTokenProvider.java
- src/main/java/aibe1/proj2/mentoss/global/config/SecurityConfig.java
- src/main/java/aibe1/proj2/mentoss/global/entity/AppUser.java
계정 관련 기능과 소셜 로그인 연동 기능을 구현했습니다.
- 소셜 로그인 연동 기능 (Google, Kakao)
- JWT 토큰에 사용자 ID 포함 기능 추가
- 사용자 인증 관련 예외 처리
- 프로필 조회 기능
- 프로필 업데이트 기능
- 생년월일 기반 나이 계산 로직
- 지역코드 유효성 검증 로직
- 프로필 완성 여부 확인 기능
- 회원 탈퇴 기능
- 아직 프로필 이미지 업로드 기능은 구현되지 않았습니다. 별도 PR로 진행 예정입니다.
> feat: 계정 관련 기능 및 소셜 로그인 연동 구현

- src/main/java/aibe1/proj2/mentoss/feature/account/controller/AccountController.java
- src/main/java/aibe1/proj2/mentoss/feature/account/model/dto/UserRegionsUpdateRequestDto.java
- src/main/java/aibe1/proj2/mentoss/feature/account/service/AccountService.java
- src/main/java/aibe1/proj2/mentoss/feature/account/service/AccountServiceImpl.java
사용자 지역 조회 및 업데이트 API를 구현했습니다
- 사용자 지역 조회 API 구현 (AccountService)
- 사용자가 설정한 지역 목록을 조회하는 기능
- 사용자 지역 업데이트 API 구현
- UserRegionsUpdateRequestDto 생성
- 사용자 지역 정보 업데이트 기능 구현
> feat: 사용자 지역 관리 API 구현

- src/main/java/aibe1/proj2/mentoss/feature/login/service/OAuth2LoginSuccessHandler.java
- src/main/java/aibe1/proj2/mentoss/global/config/SecurityConfig.java
OAuth2 소셜 로그인 기능과 프론트엔드 연동 방식을 개선하여 사용자 경험을 향상시켰습니다.
- OAuth2 로그인 성공 핸들러 개선
- 로그인 성공 시 JWT 토큰 생성 및 전달 방식 구현
- OAuth2LoginSuccessHandler 코드 리팩토링
- 중복 코드 제거 및 메서드 통합
- 예외 처리 로직 개선
> feat: OAuth2 소셜 로그인 및 프론트엔드 연동 개선

- src/main/java/aibe1/proj2/mentoss/feature/login/service/OAuth2LoginSuccessHandler.java
- src/main/java/aibe1/proj2/mentoss/global/config/SecurityConfig.java
OAuth2 인증 및 소셜 로그인 프로세스 개선 작업을 진행했습니다.
- 보안 설정 통합 및 개선
- 개발/배포 환경별 분리된 Security 설정을 단일 설정으로 통합
- OAuth2 인증 설정 개선
- API 요청에 대한 인증 오류 처리 로직 개선
- 소셜 로그인 리다이렉트 방식 개선
- 팝업 창 방식에서 직접 리다이렉트 방식으로 변경
- 프로필 환경에 따른 리다이렉트 URI 분기 처리
> fix: OAuth2 인증 및 소셜 로그인 프로세스 개선

- src/main/java/aibe1/proj2/mentoss/feature/application/controller/ApplicationController.java
- src/main/java/aibe1/proj2/mentoss/feature/application/model/dto/LectureResponseDto.java
- src/main/java/aibe1/proj2/mentoss/feature/application/model/mapper/ApplicationMapper.java
- src/main/java/aibe1/proj2/mentoss/feature/application/service/ApplicationServiceImpl.java
- src/main/java/aibe1/proj2/mentoss/feature/message/controller/MessageController.java
- src/main/java/aibe1/proj2/mentoss/feature/message/service/MessageServiceImpl.java
- 과외 조회시 빠진 dto 추가
- jwt 토큰에서 user id 추출 추가
> 과외 문의 api 

- src/main/java/aibe1/proj2/mentoss/feature/review/controller/ReviewController.java
- src/main/java/aibe1/proj2/mentoss/feature/review/model/mapper/ReviewMapper.java
- src/main/java/aibe1/proj2/mentoss/feature/review/service/ReviewService.java
- src/main/java/aibe1/proj2/mentoss/feature/review/service/ReviewServiceImpl.java
- src/main/java/aibe1/proj2/mentoss/global/config/SecurityConfig.java
- 멘토별 평균 평점 계산 API (/api/review/mentor/{mentorId}/average-rating)
- 강의별 평균 평점 계산 API (/api/review/lecture/{lectureId}/average-rating)
- 예외처리 및 API Swagger 작성 필요
- Request 및 Response에 들어갈 데이터타입 dto를 통해 정리
> 평균 평점 계산 기능 추가

- src/main/java/aibe1/proj2/mentoss/feature/message/controller/MessageController.java
- src/main/java/aibe1/proj2/mentoss/feature/message/model/mapper/MessageMapper.java
- src/main/java/aibe1/proj2/mentoss/feature/message/service/MessageServiceImpl.java
- 서비스단에서 메퍼로 보내는 인수 추가
- 받은/보낸 쪽지 user nickname 선택적으로 가지고 올 수 있게 변경
> 쪽지함 상세보기 수정

- src/main/java/aibe1/proj2/mentoss/feature/lecture/controller/LectureController.java
- src/main/java/aibe1/proj2/mentoss/feature/lecture/model/dto/response/LectureResponse.java
- src/main/java/aibe1/proj2/mentoss/feature/lecture/model/mapper/LectureMapper.java
- src/main/java/aibe1/proj2/mentoss/global/config/SecurityConfig.java
> Fix : securityConfig에서 PATCH허용

- src/main/java/aibe1/proj2/mentoss/feature/lecture/controller/LectureController.java
- src/main/java/aibe1/proj2/mentoss/feature/lecture/model/dto/response/LectureResponse.java
- src/main/java/aibe1/proj2/mentoss/feature/lecture/model/mapper/LectureMapper.java
- src/main/java/aibe1/proj2/mentoss/feature/review/controller/ReviewController.java
- src/main/java/aibe1/proj2/mentoss/feature/review/model/dto/AverageRatingResponseDto.java
- src/main/java/aibe1/proj2/mentoss/feature/review/model/mapper/ReviewMapper.java
- src/main/java/aibe1/proj2/mentoss/feature/review/service/ReviewService.java
- src/main/java/aibe1/proj2/mentoss/feature/review/service/ReviewServiceImpl.java
수업 상세 페이지 멘토프로필 옆 별점  수업별점 -> 멘토별점 으로 수정
> 수업 상세 페이지 별점 수정

- src/main/java/aibe1/proj2/mentoss/feature/account/model/mapper/AccountMapper.java
- src/main/java/aibe1/proj2/mentoss/feature/account/model/mapper/MentorMapper.java
- src/main/java/aibe1/proj2/mentoss/feature/account/service/AccountServiceImpl.java
- src/main/java/aibe1/proj2/mentoss/feature/lecture/model/mapper/LectureMapper.java
- src/main/java/aibe1/proj2/mentoss/feature/login/model/mapper/AppUserMapper.java
- src/main/java/aibe1/proj2/mentoss/feature/login/service/CustomOAuth2UserService.java
- src/main/java/aibe1/proj2/mentoss/feature/login/service/OAuth2LoginSuccessHandler.java
- src/main/java/aibe1/proj2/mentoss/global/config/SecurityConfig.java
회원 탈퇴 처리를 개선하고 소셜 로그인 관련 에러 처리를 강화했습니다.
- 탈퇴 회원의 게시 강의 자동 종료 처리
- 탈퇴한 회원 정보 익명화 처리
- 개인정보 보호 준수를 위한 데이터 익명화 구현
- 탈퇴 시 랜덤 접미사를 사용하여 사용자 정보 마스킹
- 회원 탈퇴 후 재가입 기능 개선
- 동일 소셜 계정 재가입 가능 및 사용자 경험 개선 
- 중복 이메일 소셜 로그인 제한 및 에러 처리
- 다른 소셜 계정으로 동일 이메일 가입 시도 시 명확한 에러 제공
- 프론트엔드에 소셜 타입 정보 전달하여 UX 개선
> feat: 회원 관리 기능 강화 및 소셜 로그인 개선

- src/main/java/aibe1/proj2/mentoss/feature/lecture/controller/LectureController.java
- src/main/java/aibe1/proj2/mentoss/feature/lecture/model/dto/request/LectureSearchRequest.java
- src/main/java/aibe1/proj2/mentoss/feature/lecture/model/dto/response/LectureResponse.java
- src/main/java/aibe1/proj2/mentoss/feature/lecture/model/mapper/LectureMapper.java
- src/main/java/aibe1/proj2/mentoss/feature/lecture/model/mapper/LectureSqlProvider.java
필터검색보완 
과외 게시글 수정시 지역코드 누락되는 버그 해결
> Feature/lecture Refator: 필터검색기능 보완, 

- src/main/java/aibe1/proj2/mentoss/feature/lecture/service/LectureServiceImpl.java
- src/main/java/aibe1/proj2/mentoss/feature/review/service/ReviewServiceImpl.java
- src/main/java/aibe1/proj2/mentoss/global/exception/GlobalExceptionHandler.java
- src/main/java/aibe1/proj2/mentoss/global/exception/InappropriateContentException.java
- src/main/java/aibe1/proj2/mentoss/global/moderation/model/ModerationResult.java
- src/main/java/aibe1/proj2/mentoss/global/moderation/service/ContentModerationService.java
- src/main/java/aibe1/proj2/mentoss/global/moderation/service/ContentModerationServiceImpl.java
- src/main/java/aibe1/proj2/mentoss/global/util/XssSanitizer.java
- src/main/resources/application-prod.yml
- Gemini API를 활용하여 강의 제목/소개/커리큘럼, 리뷰 내용의 부적절 콘텐츠 감지 기능 추가
- XSS 방지를 위한 정화 유틸리티 XssSanitizer 적용
- ModerationResult 모델 및 ContentModerationService 인터페이스 정의
- 유해성 차단시 InappropriateContentException 예외 발생
- GlobalExceptionHandler를 통해 사용자에게 UX 친화적인 메시지 반환
- Gemini API 토큰 길이 초과 시 관리자 알림을 위한 TODO 주석 추가
> feat: Gemini 기반 콘텐츠 유해성 필터링 기능 도입

- src/main/java/aibe1/proj2/mentoss/feature/review/service/ReviewServiceImpl.java
> feat: 리뷰 수정 시에도 유해 콘텐츠 필터링 추가

- src/main/java/aibe1/proj2/mentoss/global/moderation/service/ContentModerationServiceImpl.java
- Gemini API 요청 시 temperature: 0.0, stopSequences 등 generationConfig 적용
- 프롬프트 수정: 교육 목적 콘텐츠는 허용, 명확한 응답만 반환(ALLOWED or BLOCKED: XXX)
- 응답 후처리 로직 추가: 줄바꿈 제거, 대소문자 통일, 유효 응답만 통과
- 유효 응답 목록 상수로 관리하여 안정성 향상
- 예외 발생 시 fail-safe로 ALLOWED 처리 (서비스 중단 방지)
- application.yml에 moderation 프롬프트 및 Gemini config 명시적으로 관리
> feat(moderation): Gemini AI 기반 콘텐츠 필터링 시스템 강화

- build.gradle
- src/main/java/aibe1/proj2/mentoss/global/util/XssSanitizer.java
- Tiptap 에디터의 하이라이트 기능(mark 태그 + background-color)을 완전 지원하도록 XssSanitizer 수정
- <mark style="background-color: ..."> 및 data-color 속성 허용
- 기존 span, img, heading 태그 지원 유지
- <script>, onclick 등 위험 요소는 여전히 제거됨
> fix; Tiptap 호환성 개선

- src/main/java/aibe1/proj2/mentoss/feature/application/controller/ApplicationController.java
- src/main/java/aibe1/proj2/mentoss/feature/application/model/dto/LectureApplicantRawDto.java
- src/main/java/aibe1/proj2/mentoss/feature/application/model/mapper/ApplicationMapper.java
- src/main/java/aibe1/proj2/mentoss/feature/application/service/ApplicationServiceImpl.java
> 과외 문의 리스트 수정

- src/main/java/aibe1/proj2/mentoss/feature/account/controller/AccountController.java
- src/main/java/aibe1/proj2/mentoss/feature/account/model/dto/MentorPublicProfileDto.java
- src/main/java/aibe1/proj2/mentoss/feature/account/model/mapper/MentorMapper.java
- src/main/java/aibe1/proj2/mentoss/feature/account/service/AccountService.java
- src/main/java/aibe1/proj2/mentoss/feature/account/service/AccountServiceImpl.java
멘토 프로필에서 유저 정보 + 멘토 프로필 정보를 전부 보여주기 위한 API를 추가했습니다.
> feat : 멘토 ID 기반 프로필 조회 API 추가

- src/main/java/aibe1/proj2/mentoss/feature/account/controller/AccountController.java
- src/main/java/aibe1/proj2/mentoss/feature/account/service/AccountServiceImpl.java
> refactor: 닉네임 제한 12자로 변경

- src/main/java/aibe1/proj2/mentoss/feature/application/model/mapper/ApplicationMapper.java
> fix: 버그 수정

- src/main/java/aibe1/proj2/mentoss/feature/application/model/mapper/ApplicationMapper.java
> fix: 매칭취소 버그 수정
